### ISSUE TITLE
Adding custom locale types

### ISSUE THREAD

**Issue by Hopson97** [forwardemail/email-templates#397]
Hi there, 

I was wondering if it is possible to add customisable locale codes for this package? For example, the locale `es-LA` is invalid for use but is it possible to create a custom locale type so that it can be used?

Thanks!

**Comment by niftylettuce** [comment]
Not right now.  You'd have to make a PR to `@ladjs/i18n` to use something custom for validation instead of what we use, which is`i18n-locales`.

https://github.com/ladjs/i18n/blob/eed5ec08067eaad29e53dddd999f590d5acc5906/src/index.js#L6
https://github.com/ladjs/i18n/blob/eed5ec08067eaad29e53dddd999f590d5acc5906/src/index.js#L57-L63

**Comment by Hopson97** [comment]
Ah OK no worries, thanks anyways.
